@baseUrl=https://localhost:5001/-/api


GET {{baseUrl}}

###

POST {{baseUrl}}
Content-Type: application/json

{
    "name" : "Ronald"
}

###

//REGISTER
POST {{baseUrl}}/auth/signup
Content-Type: application/json

{
  "first" : "paul",
  "email" : "dave5@aol.com",
  "password" : "bigSafePassword4d5ed5sdf6@#$",
  "confirmpassword" : "bigSafePassword4d5ed5sdf6@#$"
}

###

//LOGIN
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email" : "dave5@aol.com",
  "password" : "bigSafePassword4d5ed5sdf6@#$"
}

###

//TEST AUTH
GET {{baseUrl}}/auth-test

###

//TEST AUTH WITH BEARER JWT
GET {{baseUrl}}/auth-test
Authorization: Bearer CfDJ8MlgwzBTFQxOhbqBKzMA5DlRHvR6kp-X1aQJPkfY2BRU_11UG4NhFyroGgizO-h8GHF-UUPO-udvgdxlupYbApN1fDEKf5Bap5fMtKKoUZek5RfI7ipAmVTs-IQWQuwANVmqv2nds0a4gO30dtOKRorh0PHjAqVeKVhIHe9FSVvma2FlCjpG70pvp-NqFu6XyW17j6u8gAuJiTjn2Jlw9zYe2j3l6chvZhroun-Vr2HzkdVl5dKUuH_TmcPC7bOnDqbHQo45gXzjUCiHyvDPyLDuruQE79wcQk6KxukrCAWx0ZGlsnv-9uCB8OJyLOb5_a5RhPDt6RjRvJaZ912qtUb4EZQjm12YpBS2CboLlmAVM-SEd1b-23AAzJ-Z2aVtZ8nDa4--2SSV_2yLrTnr_0c_-aCDZGyB0q1qaCFq-w8V-B6jhhcVo4wBmgtl-UReYFJnYNscJ6pY72t3fBrnc-GNraMOaehXz4OLJsnczhUvCC5jcuxGzXaHwgE8AS55Q4Ae9d054xBIrX4er8BCokIqs9x1oBHd2mn-QfwcD7hnZNSFgJVzZ6RNEMdvyPTmn678UKppr8459-A47BJN9EeOBCJxphohCzAFpSC18ln32wXPtNKwJZDsS_6DIzUsV_lKkeY69dE6vMD1TwVrnA8JlX_Q1ULozuaz41Bx5uNugIw5Jz3hSOL4wNKM-4nuig
###

//CREATE SHORT URL
POST {{baseUrl}}/url/create
Content-Type: application/json

{
  "longUrl" : "http://launchcode.org"
}
###

//GET SHORT URL REDIRECT TO LONG URL
GET {{baseUrl}}/url/redirect/aaa
###