@baseUrl=https://localhost:5001/-/api


GET {{baseUrl}}

###

POST {{baseUrl}}
Content-Type: application/json

{
  "name" : "Ronald"
}

###

//REGISTER
POST {{baseUrl}}/auth/signup
Content-Type: application/json

{
  "first" : "paul",
  "email" : "dave5@aol.com",
  "password" : "bigSafePassword4d5ed5sdf6@#$",
  "confirmpassword" : "bigSafePassword4d5ed5sdf6@#$"
}

###

//LOGIN
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email" : "dave5@aol.com",
  "password" : "bigSafePassword4d5ed5sdf6@#$"
}

###

//TEST AUTH
GET {{baseUrl}}/auth-test

###

//TEST AUTH WITH BEARER JWT
GET {{baseUrl}}/auth-test
Authorization: Bearer CfDJ8MlgwzBTFQxOhbqBKzMA5DnC3Tc2jJOreHDn-1QOomRiRHjfipPRyxC6c9qCcjvxYwX9xX_9C04W47u3m2M8ht3smjzxOD29OFxqXVsgidIbBTOXShkgQQwXUIhX8vQ8f0CVn2a3LX0EOOnsp3QgouTCopa1LByHjDP3CfGkkSuh8gxeOeXfmM_z9IvAQd95_p5JRCR2dLbGazx8jYkHBQo0WA3IkA7pVYf-YNU1nhL09dGlss5_V6tziYJyemubSHS2hIQd2fKnQ4R9vX65czyRZCbnCFYIKyBqfaSmLAX0fttN1_WGIUDICpC0bZ13UvM5tVYO0nEkyc49ykyB-mvW2Se47i2gl2kgPBTElwBceEbqeFTFNNDmp5OtCoRie3fDhYp54pqgbjHbYc5wUNN5rj5aWzPOnNVdtCrPt0kGszw9Jpl1lvTqyx2Y2SUA8zOFwnJi0GFlp5LCXXaopPYDlXJu_LV54a4kQKhyQp26G-wHL0lRflAvyP7fR_SN-ipfK6R67luK3WxpYtRnLme08VqRQSfy-T9I7mS-YUn_Ys1Jhsogn_Uz6i1EWNG8jIc16x_talFr8K1_XNzDFhnfHCfpHUhhgOMeOk-G50pTR_nwdTl3lZ1Q7F77CSvVMwXPSOgdSoJWBI-PIwz0XhvQXTkxQ-hYsi11jAgCW6eeDQQ4L--G65-PQaA3J3O61w
###

//GET SHORT URL REDIRECT TO LONG URL
POST {{baseUrl}}/url/create
Content-Type: application/json

{
  "longUrl" : "http://launchcode.org"
}
###

//GET SHORT URL REDIRECT TO LONG URL
GET {{baseUrl}}/url/redirect/aaa
###